In [2]:
# Needed libraries 


# System requiremenmts 
import time
import random
import datetime as dt
import os 

import requests
import time

# Data Management 
import pandas as pd


# Parameters 
URL_CHARGERS = "https://www.tesla.com/findus/list/chargers/Mexico"
URL_SUPERCHARGERS = "https://www.tesla.com/findus/list/superchargers/Mexico"

In [3]:
EMAIL = os.getenv("OSM_EMAIL")

In [4]:

def get_coordinates_nominatim(address: str, email: str):
    """
    Given a text address, return (lat, lon) using Nominatim (OpenStreetMap)
    """
    url = "https://nominatim.openstreetmap.org/search"
    params = {
        "q": address,
        "format": "json",
        "limit": 1
    }

    headers = {
        "User-Agent": f"your-app-name/1.0 ({email})"
    }

    response = requests.get(url, params=params, headers=headers, timeout=10)
    response.raise_for_status()

    data = response.json()

    if not data:
        return None, None

    return float(data[0]["lat"]), float(data[0]["lon"])

In [5]:
df = pd.read_csv("mexico_chargers_address.csv")

In [6]:
df.tail(3)

,location_label,description,charger_type
518,"Villa Hidalgo, SLP","78973 Villa de Hidalgo, San Luis Potosi, Villa...",super_charger
519,"Santa Ana, SON","901 5 de Mayo, La Loma, Santa Ana, Sonora 84600",super_charger
520,"Valladolid, YUC","KM 152+700 Autopista Mérida-Cancún, Valladolid...",super_charger

In [7]:

def get_coordinates_nominatim(address: str, email: str):
    """
    Given a text address, return (lat, lon) using Nominatim (OpenStreetMap)
    """
    url = "https://nominatim.openstreetmap.org/search"
    params = {
        "q": address,
        "format": "json",
        "limit": 1
    }

    headers = {
        "User-Agent": f"your-app-name/1.0 ({email})"
    }

    time.sleep(random.uniform(1,1.3))

    

    response = requests.get(url, params=params, headers=headers, timeout=10)
    response.raise_for_status()

    data = response.json()

    if not data:
        return None, None

    return float(data[0]["lat"]), float(data[0]["lon"])

In [8]:

df[["lat", "lon"]] = df["description"].apply(
    lambda x: pd.Series(get_coordinates_nominatim(x,EMAIL))
)

In [10]:
df

,location_label,description,charger_type,lat,lon
0,Fiesta Americana Aguascalientes,"Calle Los Laureles S/N Las Flores, Aguascalien...",charger,NaN,NaN
1,Fiesta Inn Aguascalientes,Calle Mahatma Gandhi #302 Sur Prados de Villas...,charger,NaN,NaN
2,One Aguascalientes San Marcos,"Los Laureles No. 404 Fracc. Las Flores, Aguasc...",charger,NaN,NaN
3,Adobe Guadalupe,"Parcela A-1 s/n Rusa de Guadalupe, Ensenada, B...",charger,NaN,NaN
4,Bajamar,"Ensenada, Carretera Tijuana - Ensenada Km. 77....",charger,NaN,NaN
...,...,...,...,...,...
516,"Cancún, QRO","SM 46 Carr. Cancún, Cancun, Querétaro 77560",super_charger,NaN,NaN
517,"Matehuala, SLP","57 Tramo Matehuala-Saltillo KM. 11 + 385.49, M...",super_charger,NaN,NaN
518,"Villa Hidalgo, SLP","78973 Villa de Hidalgo, San Luis Potosi, Villa...",super_charger,22.451729,-100.676307
519,"Santa Ana, SON","901 5 de Mayo, La Loma, Santa Ana, Sonora 84600",super_charger,NaN,NaN
520,"Valladolid, YUC","KM 152+700 Autopista Mérida-Cancún, Valladolid...",super_charger,NaN,NaN

In [16]:
df.loc[5, "description"]

'Carretera Tecate Ensenada Km. 74 Valle de Guadalupe, Ensenada, Baja California 22760'