In [2]:
# Needed libraries 


# System requiremenmts 
import time
import random
import datetime as dt
import os 

import requests
import time

# Data Management 
import pandas as pd


# Parameters 
URL_CHARGERS = "https://www.tesla.com/findus/list/chargers/Mexico"
URL_SUPERCHARGERS = "https://www.tesla.com/findus/list/superchargers/Mexico"

In [22]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("risheepanchal/global-ev-charging-stations-dataset")

ModuleNotFoundError: No module named 'kagglehub'

In [24]:
# Web Scrapping 
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.actions.action_builder import ActionBuilder
from selenium.webdriver.common.actions.key_input import KeyInput
from selenium.webdriver.common.actions.pointer_input import PointerInput
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
import undetected_chromedriver as uc
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait

In [3]:
EMAIL = os.getenv("OSM_EMAIL")

In [4]:

def get_coordinates_nominatim(address: str, email: str):
    """
    Given a text address, return (lat, lon) using Nominatim (OpenStreetMap)
    """
    url = "https://nominatim.openstreetmap.org/search"
    params = {
        "q": address,
        "format": "json",
        "limit": 1
    }

    headers = {
        "User-Agent": f"your-app-name/1.0 ({email})"
    }

    response = requests.get(url, params=params, headers=headers, timeout=10)
    response.raise_for_status()

    data = response.json()

    if not data:
        return None, None

    return float(data[0]["lat"]), float(data[0]["lon"])

In [3]:
df = pd.read_csv("mexico_chargers_address.csv")

In [19]:
df.dropna()

,location_label,description,charger_href,charger_type
0,Fiesta Americana Aguascalientes,"Calle Los Laureles S/N Las Flores, Aguascalien...",https://www.tesla.com/findus/location/charger/...,charger
1,Fiesta Inn Aguascalientes,Calle Mahatma Gandhi #302 Sur Prados de Villas...,https://www.tesla.com/findus/location/charger/...,charger
2,One Aguascalientes San Marcos,"Los Laureles No. 404 Fracc. Las Flores, Aguasc...",https://www.tesla.com/findus/location/charger/...,charger
3,Adobe Guadalupe,"Parcela A-1 s/n Rusa de Guadalupe, Ensenada, B...",https://www.tesla.com/findus/location/charger/...,charger
4,Bajamar,"Ensenada, Carretera Tijuana - Ensenada Km. 77....",https://www.tesla.com/findus/location/charger/...,charger
...,...,...,...,...
971,Urban Center Merida,"Avenida Camara de Comercio 174 Monterreal, M├⌐...",https://www.tesla.com/findus/location/charger/...,super_charger
972,Fiesta Inn Zacatecas,Calzada Heroes de Chapultepec km 13 + 200 La E...,https://www.tesla.com/findus/location/charger/...,super_charger
973,Hotel Baruk Teleferico,"Paseo Diaz Ordaz 602 Zacatecas Centro, Zacatec...",https://www.tesla.com/findus/location/charger/...,super_charger
974,Mision Zacatecas,"Av. Hidalgo 407 Zacatecas Centro, Zacatecas, Z...",https://www.tesla.com/findus/location/charger/...,super_charger
975,Spa Hacienda Baruk,"Blvd. Heroes de Chapultepec 801 La Escondida, ...",https://www.tesla.com/findus/location/charger/...,super_charger

In [ ]:
hrefs = df.charger_href.drop_duplicates().to_list()

In [22]:
url = hrefs[0]

In [ ]:
def human_sleep(a=0.8, b=2.3):
    time.sleep(random.uniform(a, b))


options = uc.ChromeOptions()
options.add_argument("--start-maximized")
options.add_argument("--disable-blink-features=AutomationControlled")
options.add_argument("--no-sandbox")
options.add_argument("--disable-dev-shm-usage")
options.binary_location = "/usr/bin/google-chrome"

driver = uc.Chrome(options=options)
wait = WebDriverWait(driver, 25)

driver.get(url)

original_window = driver.current_window_handle


human_sleep(3, 4)

button = driver.find_element(By.CSS_SELECTOR, "button[class*='tds-btn']")

button.click()

WebDriverWait(driver, 10).until(
    lambda d: len(d.window_handles) > 1
)

# Switch to the new window
for handle in driver.window_handles:
    if handle != original_window:
        driver.switch_to.window(handle)
        break

# Get the URL
new_window_url = driver.current_url
new_window_url = new_window_url[new_window_url.index("daddr=")+6:]

coords = [float(x) for x in new_window_url.split(",")]

lat, lon = coords[0],coords[1]

print(lat,lon)

driver.quit()

ValueError: invalid literal for int() with base 10: '21.875751'

In [7]:

def get_coordinates_nominatim(address: str, email: str):
    """
    Given a text address, return (lat, lon) using Nominatim (OpenStreetMap)
    """
    url = "https://nominatim.openstreetmap.org/search"
    params = {
        "q": address,
        "format": "json",
        "limit": 1
    }

    headers = {
        "User-Agent": f"your-app-name/1.0 ({email})"
    }

    time.sleep(random.uniform(1,1.3))

    

    response = requests.get(url, params=params, headers=headers, timeout=10)
    response.raise_for_status()

    data = response.json()

    if not data:
        return None, None

    return float(data[0]["lat"]), float(data[0]["lon"])

In [8]:

df[["lat", "lon"]] = df["description"].apply(
    lambda x: pd.Series(get_coordinates_nominatim(x,EMAIL))
)

In [10]:
df

,location_label,description,charger_type,lat,lon
0,Fiesta Americana Aguascalientes,"Calle Los Laureles S/N Las Flores, Aguascalien...",charger,NaN,NaN
1,Fiesta Inn Aguascalientes,Calle Mahatma Gandhi #302 Sur Prados de Villas...,charger,NaN,NaN
2,One Aguascalientes San Marcos,"Los Laureles No. 404 Fracc. Las Flores, Aguasc...",charger,NaN,NaN
3,Adobe Guadalupe,"Parcela A-1 s/n Rusa de Guadalupe, Ensenada, B...",charger,NaN,NaN
4,Bajamar,"Ensenada, Carretera Tijuana - Ensenada Km. 77....",charger,NaN,NaN
...,...,...,...,...,...
516,"Cancún, QRO","SM 46 Carr. Cancún, Cancun, Querétaro 77560",super_charger,NaN,NaN
517,"Matehuala, SLP","57 Tramo Matehuala-Saltillo KM. 11 + 385.49, M...",super_charger,NaN,NaN
518,"Villa Hidalgo, SLP","78973 Villa de Hidalgo, San Luis Potosi, Villa...",super_charger,22.451729,-100.676307
519,"Santa Ana, SON","901 5 de Mayo, La Loma, Santa Ana, Sonora 84600",super_charger,NaN,NaN
520,"Valladolid, YUC","KM 152+700 Autopista Mérida-Cancún, Valladolid...",super_charger,NaN,NaN

In [16]:
df.loc[5, "description"]

'Carretera Tecate Ensenada Km. 74 Valle de Guadalupe, Ensenada, Baja California 22760'

In [11]:
df_osm = pd.read_csv("mexico_chargers_coords.csv")
df = pd.read_csv("mexico_chargers_address.csv")

In [12]:
visited_list = df_osm.charger_href.drop_duplicates().to_list()

In [15]:
df_pend = df.query(f""" charger_href not in {visited_list}""")

In [16]:
df_pend

,location_label,description,charger_href,charger_type
0,Fiesta Americana Aguascalientes,"Calle Los Laureles S/N Las Flores, Aguascalien...",https://www.tesla.com/findus/location/charger/...,charger
1,Fiesta Inn Aguascalientes,Calle Mahatma Gandhi #302 Sur Prados de Villas...,https://www.tesla.com/findus/location/charger/...,charger
2,One Aguascalientes San Marcos,"Los Laureles No. 404 Fracc. Las Flores, Aguasc...",https://www.tesla.com/findus/location/charger/...,charger
3,Adobe Guadalupe,"Parcela A-1 s/n Rusa de Guadalupe, Ensenada, B...",https://www.tesla.com/findus/location/charger/...,charger
4,Bajamar,"Ensenada, Carretera Tijuana - Ensenada Km. 77....",https://www.tesla.com/findus/location/charger/...,charger
...,...,...,...,...
971,Urban Center Merida,"Avenida Camara de Comercio 174 Monterreal, M├⌐...",https://www.tesla.com/findus/location/charger/...,super_charger
972,Fiesta Inn Zacatecas,Calzada Heroes de Chapultepec km 13 + 200 La E...,https://www.tesla.com/findus/location/charger/...,super_charger
973,Hotel Baruk Teleferico,"Paseo Diaz Ordaz 602 Zacatecas Centro, Zacatec...",https://www.tesla.com/findus/location/charger/...,super_charger
974,Mision Zacatecas,"Av. Hidalgo 407 Zacatecas Centro, Zacatecas, Z...",https://www.tesla.com/findus/location/charger/...,super_charger
975,Spa Hacienda Baruk,"Blvd. Heroes de Chapultepec 801 La Escondida, ...",https://www.tesla.com/findus/location/charger/...,super_charger

In [18]:
# Web Scrapping 
import random
import time
import undetected_chromedriver as uc

from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

def human_sleep(a=0.8, b=2.3):
    time.sleep(random.uniform(a, b))

In [21]:
# List of references 
hrefs = df_pend.charger_href.to_list()
desc = df_pend.charger_href.to_list()

# Results list init 
results = []

failed_count = 0

# Link open loops 
for url, d in zip(hrefs, desc):

    # Anti bot detection configurration 
    options = uc.ChromeOptions()
    options.add_argument("--start-maximized")
    options.add_argument("--disable-blink-features=AutomationControlled")
    options.add_argument("--no-sandbox")
    options.add_argument("--disable-dev-shm-usage")
    options.binary_location = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"

    # Call the driver 
    driver = uc.Chrome(options=options)
    wait = WebDriverWait(driver, 25)

    try:
        driver.get(url)

        original_window = driver.current_window_handle

        human_sleep(3, 4) 
        button = driver.find_element(By.CSS_SELECTOR, "button[class*='tds-btn']") 
        button.click()

        WebDriverWait(driver, 10).until(
            lambda d: len(d.window_handles) > 1
        )

        # Switch to the new window
        for handle in driver.window_handles:
            if handle != original_window:
                driver.switch_to.window(handle)
                break

        # Get the URL
        new_window_url = driver.current_url

        # Get the text of interes 
        new_window_url = new_window_url[new_window_url.index("daddr=")+6:]

        # Transorm text into float 
        coords = [float(x) for x in new_window_url.split(",")]
        lat, lon = coords[0], coords[1]
        failed_count = 0

        print(f"Coordinate process completed for {url}. ")

    except Exception as e:
        lat, lon = 0.0, 0.0
        failed_count +=1
        print(f"Coordinate process failed for {url}. ")

    if failed_count > 10:
        break

    # Append extraction results if any 
    results.append({
            "charger_href": url,
            "lat": lat,
            "lon": lon ,
        })

    driver.quit()

# Results DataFrame
df_coords = pd.DataFrame(results)

df_coords.to_csv("coords_manual_part_1.csv", index = False)

Coordinate process completed for https://www.tesla.com/findus/location/charger/dc20460.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc20461.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc20459.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc24765.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc26308.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc20181.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc22851.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc19970.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc19722.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc20704.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc20696.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc20695.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc53612.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc90063.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc42890.
Coordinate process completed for https://www.tesla.com/findus/location/charger/STE2022022200154.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc55065.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc44721.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc26738.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc21859.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc23509.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc32936.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc67757.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc67756.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc21458.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc27440.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc20834.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc20809.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc17440.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc35887.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc17443.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc23030.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc26315.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc67767.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc33799.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc67765.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc26313.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc21429.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc67758.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc67769.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc28626.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc37536.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc37538.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc44708.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc32710.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc67768.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc20942.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc18526.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc20699.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc20701.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc42093.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc31109.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc32937.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc23372.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc32542.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc25991.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc38901.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc25147.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc25146.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc25913.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc35839.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc35840.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc30216.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc29400.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc56853.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc30901.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc20037.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc18769.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc23057.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc42720.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc46369.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc31377.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc26536.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc30516.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc31376.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc31379.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc30514.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc14491.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc51604.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc18528.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc18529.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc18531.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc35838.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc61804.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc17347.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc21301.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc17921.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc33040.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc31374.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc17450.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc55496.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc21432.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc29934.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc21300.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc39161.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc19072.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc22767.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc21426.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc22766.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc20923.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc22739.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc21695.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc23772.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc23773.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc23771.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc26363.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc17346.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc25998.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc33407.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc31375.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc33412.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc23374.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc23376.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc23375.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc23377.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc20941.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc34747.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc49612.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc24635.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc29404.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc25215.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc24636.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc20705.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc25145.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc29517.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc29878.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc25162.
Coordinate process completed for https://www.tesla.com/findus/location/charger/STE2022022200186.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc28719.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc28718.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc85939.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc22976.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc21861.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc29866.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc23141.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc22975.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc21860.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc20924.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc29853.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc32000.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc96543.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc29882.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc25150.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc18020.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc49168.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc18576.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc28572.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc29852.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc29850.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc17455.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc61792.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc20917.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc20920.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc20919.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc18530.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc20918.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc20474.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc20475.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc27535.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc29931.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc29862.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc29880.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc25479.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc48623.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc21430.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc33080.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc23958.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc20944.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc20921.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc20922.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc20943.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc29939.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc32846.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc20702.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc20462.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc19994.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc32835.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc37801.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc26146.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc29867.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc26534.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc18094.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc33249.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc30428.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc32159.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc31867.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc18740.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc32952.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc22855.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc18737.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc17759.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc17993.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc39530.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc23142.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc38363.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc38345.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc28239.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc20477.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc20478.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc31110.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc874040789.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc20680.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc26736.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc26737.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc28430.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc26416.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc35613.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc55049.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc55555.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc18533.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc20457.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc18534.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc29936.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc75436.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc33457.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc20360.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc42118.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc25148.
Coordinate process completed for https://www.tesla.com/findus/location/charger/dc35612.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc46368.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc26726.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc32002.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc17397.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc29514.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc27778.
Coordinate process failed for https://www.tesla.com/findus/location/charger/dc20925.
Coordinate process failed for https://www.tesla.com/findus/location/charger/453076.
Coordinate process failed for https://www.tesla.com/findus/location/charger/453323.
Coordinate process failed for https://www.tesla.com/findus/location/charger/453324.
Coordinate process failed for https://www.tesla.com/findus/location/charger/453325.

Roads processing

In [4]:
RAW_DATA = "../../data/raw/nat_road_net_mex/conjunto_de_datos/"
SHP_FILE = "red_vial.shp"

In [5]:
import geopandas as gpd

In [6]:
gdf = gpd.read_file(RAW_DATA + SHP_FILE)

DataSourceError: ../../data/raw/nat_road_net_mex/conjunto_de_datos/red_vial.shp: No such file or directory

In [7]:
gdf.size

NameError: name 'gdf' is not defined

In [8]:
gdf.head(10)#.plot()

NameError: name 'gdf' is not defined